### ISSUE TITLE
Use Vault for storing and manage secrets

### ISSUE THREAD

**Issue by rdcm** [rdcm/coin-board#4]
Needed helm chart for using vault.

Secrets like this must be removed from code:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana.name }}-config
  namespace: {{ .Values.namespace }}
data:
  GF_SECURITY_ADMIN_PASSWORD: "admin"  # TODO move to secret
```
